<?php

/*
===============================================================================
===============================================================================
                    WARNING: DO NOT EDIT THIS FILE
===============================================================================
===============================================================================

                       ⚠️  IMPORTANT NOTICE ⚠️

    This file is critical for the operation of the application.
    Any modifications may lead to unexpected behavior or
    system failures. Please proceed with caution!

===============================================================================
===============================================================================

             ⚠️  Please connect the Telegram webhook to this file.  ⚠️

To connect the Telegram webhook using the API, follow these steps:
1. Open your Telegram app and search for the BotFather.
2. Start a chat with BotFather and create a new bot using the command `/newbot`.
3. After creating your bot, you will receive a token. Copy this token.
4. Make a POST request to the Telegram API to set your webhook.
   POST https://api.telegram.org/bot<YourWebhookURL>/setWebhook?url=<YourUrl>
   Replace `<YourBotToken>` with your bot token and `<YourWebhookURL>` with the URL of this file.

5. You should receive a JSON response indicating whether the webhook was set successfully.

===============================================================================
*/

use natilosir\bot\Route;

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/natilosir/bot/src/log.php';

require_once 'Router/route.php';
Route::init();

