<?php




/*
===============================================================================
===============================================================================
                    WARNING: DO NOT EDIT THIS FILE
===============================================================================
===============================================================================

                       ⚠️  IMPORTANT NOTICE ⚠️

    This file is critical for the operation of the application.
    Any modifications may lead to unexpected behavior or 
    system failures. Please proceed with caution!

===============================================================================
===============================================================================

             ⚠️  Please connect the Telegram webhook to this file.  ⚠️

To connect the Telegram webhook using the API, follow these steps:
1. Open your Telegram app and search for the BotFather.
2. Start a chat with BotFather and create a new bot using the command `/newbot`.
3. After creating your bot, you will receive a token. Copy this token.
4. Make a POST request to the Telegram API to set your webhook. 
   POST https://api.telegram.org/bot<YourWebhookURL>/setWebhook?url=<YourUrl>
   Replace `<YourBotToken>` with your bot token and `<YourWebhookURL>` with the URL of this file.

5. You should receive a JSON response indicating whether the webhook was set successfully.

===============================================================================
*/







require __DIR__ . '/vendor/autoload.php';







require __DIR__ . '/vendor/natilosir/bot/src/log.php';
setupErrorHandling();

$data = json_decode(file_get_contents('php://input'));
$message = $data->message;
if ($message) {
    $text       = $message->text;
    $chatID     = $message->chat->id;
    $fromID     = $message->from->id;
    $firstName  = $message->from->first_name;
    $lastName   = $message->from->last_name;
    $username   = $message->from->username;
    $date       = $message->date;
    $message_id = $message->message_id;
}
require_once "route.php";



    
$callbackQuery = $data->callback_query;
if ($callbackQuery) {
    $query_id      = $callbackQuery->id;
    $callbackData  = $callbackQuery->data;
    $chatID        = $callbackQuery->message->chat->id;
    $message_id    = $callbackQuery->message->message_id;
    $fromID        = $callbackQuery->from->id;
    $firstName     = $callbackQuery->from->first_name;
    $lastName      = isset($callbackQuery->from->last_name) ? $callbackQuery->from->last_name : null;
    $username      = isset($callbackQuery->from->username) ? $callbackQuery->from->username : null;
}
require_once "callback.php";


processLogFile();
