<?php

require __DIR__ . '/vendor/autoload.php';




/*
==========================================
==========================================
      WARNING: DO NOT EDIT THIS FILE
==========================================
==========================================
*/







require __DIR__ . '/vendor/natilosir/bot/src/log.php';
setupErrorHandling();

$data = json_decode(file_get_contents('php://input'));
$message = $data->message;
if ($message) {
    $text       = $message->text;
    $chatID     = $message->chat->id;
    $fromID     = $message->from->id;
    $firstName  = $message->from->first_name;
    $lastName   = $message->from->last_name;
    $username   = $message->from->username;
    $date       = $message->date;
    $message_id = $message->message_id;
}
    require_once "route.php";

processLogFile();
